/*
* @author anderson.silva
*/

@isTest
public class AccountValidatorTest {

        //BDD given When Then
        @isTest
        static void validateDocumentNumberTest() {

            // List<Account> accounts = new List<Account> {
            //     AccountFixtureFactory.createAccount('Teste01', 100000000, Account.Type.PREMIUM, '48913722062'),
            //     AccountFixtureFactory.createAccount('Teste02', 15000, Account.Type.PREMIUM, '11111111111')
            // };

            // AccountValidator validator = new AccountValidator();

            // List<Account> validatededAccounts = filter.validateDocumentNumberTest(accounts);

            // System.assertEquals(accounts.size(), validatededAccounts.size());

        }
        //validatePremiumAccountTest
        //schedulingEventTest

}